from django.contrib import admin
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/users/token/', views.CustomTokenObtainPairView.as_view(),name='token_obtain_pair'), 
    path('api/users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/logout/', views.logout, name='auth_logout'),
    path('api/users/register/',views.register),
    path('api/users/reset-password/',views.reset_password),
    path('api/users/<str:username>/setup/',views.setupAccount,name='setup_account'),
    path('api/users/<str:username>/types',views.manage_types),
    path('api/users/<str:username>/types_edit',views.edit_types),
    path('api/users/<str:username>/<str:type>',views.get_type),
    path('api/users/<str:username>/supplies/',views.manage_supplies,name='manage_supplies'),
    path('api/users/<str:username>/buy-supplies/',views.reciepts,name='reciepts'),
    path('api/users/<str:username>/search_reciepts/<str:query>',views.search_Reciepts,name='search_reciepts'),
    path('api/users/<str:username>/edit-reciepts/', views.edit_reciepts, name='edit_reciepts'),
    path('api/users/<str:username>/edit-supplies/', views.edit_supplies, name='edit_supplies'),
    path('api/users/<str:username>/search/<str:query>', views.search_types_and_supplies, name='search_types_and_supplies'),
    path('api/users/<str:username>/search-supplies/<str:type>/<str:query>', views.search_supplies, name='search_supplies'),
    path('api/users/<str:username>/search-supplies/<str:query>', views.search_only_supplies, name='search_supplies'),
    path('api/users/<str:username>/employ-employees/', views.employ_Employees, name='employ-employees'),
    path('api/users/<str:username>/edit-employees/', views.edit_employee, name='edit_employee'),
    path('api/users/<str:username>/search-employees/<str:query>', views.search_Employee, name='search_employee'),
    path('api/users/<str:username>/manage-customers/', views.manage_customers),
    path('api/users/<str:username>/edit-customers/', views.edit_customers),
    path('api/users/<str:username>/search-customers/<str:customer>/', views.search_customers),
    path('api/users/<str:username>/manage-income/', views.manage_Income),
    path('api/users/<str:username>/edit-income/', views.edit_Income),
    path('api/users/<str:username>/search-income/<str:query>/', views.search_Income),
    path('api/users/<str:username>/manage-payment/', views.manage_payment),
    path('api/users/<str:username>/edit-payment/', views.edit_payment),
    path('api/users/<str:username>/search-payment/<str:query>/', views.search_payment),
    path('api/users/<str:username>/sell-customer/', views.customer_Sell),
    path('api/users/<str:username>/edit-customer-sell/', views.edit_customerSell),
    path('api/users/<str:username>/search-customer-sell/<str:query>/', views.search_CustomerSell),
    path('api/users/<str:username>/sell-customer/', views.customer_Sell),
    path('api/users/<str:username>/edit-customer-sell/', views.edit_customerSell),
    path('api/users/<str:username>/search-customer-sell/<str:query>/', views.search_CustomerSell),
    path('api/users/<str:username>/sell-supplies/', views.sells),
    path('api/users/<str:username>/edit-sell/', views.edit_sells),
    path('api/users/<str:username>/search-sell/<str:query>/', views.search_sells),
    path('api/users/<str:username>/dispatch-supplies/', views.dispatches),
    path('api/users/<str:username>/edit-dispatches/', views.edit_dispatches),
    path('api/users/<str:username>/search-dispatched/<str:query>/', views.search_dispatches),
    path('api/users/<str:username>/money-funds/', views.get_fund),
    path('api/users/<str:username>/move-sells-funds/', views.move_fund_fromSells_to_perma),
    path('api/users/<str:username>/generate-inventory/', views.generate_inventory),
    path('api/users/<str:username>/delete-inventory/', views.delete_inventory),
    path('api/users/<str:username>/search-inventory/<str:query>/', views.search_inventory),
    path('api/users/calculate/', views.ImageAnalysisView.as_view()),
    path('api/data/export/export-excel/<str:username>/', views.export_all_data_excel, name='export_all_data_excel'),
    path('api/data/import/<str:username>/', views.import_Data, name='import'),
    path('api/data/export/export-pdf/<str:username>/', views.export_all_data_pdf, name='export_all_data_pdf'),

]
