# Generated by Django 5.1.4 on 2025-05-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='profits',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
