# Generated by Django 5.1.4 on 2025-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_inventory_profits'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sales_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
